### ISSUE TITLE
Question about optimization

### ISSUE THREAD

**Issue by Bleach665** [laurentkneip/opengv#100]
I have several cameras and dataset with flat (chessboard) pattern. 
My goal is accurately estimate intrinsic, distortion and extrinsic of each camera to track objects in this cameras coordinate space using triangulation.
For each camera I perform single calibration to find intrinsic and distortion. After I make stereo calibration for all camera pair. But the result is unsatisfactory. I did all this with the OpenCV. 
Can I use OpenGV
`11. non-linear optimization over n correspondences (both central and non-central)`
to improving the accuracy of previously found cameras parameters? (Global optimization all camera parameter together.)

**Comment by ferreram** [comment]
If you want to perform an accurate calibration of your camera system you should try to use the Kalibr library: https://github.com/ethz-asl/kalibr
