### ISSUE TITLE
Epnp wrong assert()?

### ISSUE THREAD

**Issue by urbste** [laurentkneip/opengv#14]
Hey,
first I would like to thank you for sharing your great toolbox!

In think the assertion in the epnp method is incorrect
  //starting from 4 points, we have a unique solution
  assert(indices.size() > 5);

It should probably be:
  //starting from 4 points, we have a unique solution
  assert(indices.size() >= 4);

Cheers
Steffen

**Comment by laurentkneip** [comment]
Hi,

Thanks for the interest. The comment sounds indeed strange, but the code is
right. EPnP is a linearized solver that needs at leads 6 points. It solves
for four control points in the camera frame, thus 3*4=12 variables, for
which one needs 6 points.

Cheers,
laurent
