### ISSUE TITLE
Typo in CMakeLists.txt of python

### ISSUE THREAD

**Issue by gilbert1991** [laurentkneip/opengv#27]
You missed an 'S' for 'Boost_LIBRARY_DIRS' which makes the installation failed at 98% with error `No rule to make target /libboost_python.a, needed by lib/pyopengv.so`.

**Comment by paulinus** [comment]
My bad here. My cmake version actually creates a `Boost_LIBRARY_DIR` (without S). In case there were more than one dir, that line would fail anyway. So the solution is not to add the S, but to reference Boost_LIBRARIES instead. Will prepare a PR.

Thanks for spotting @gilbert1991
