### ISSUE TITLE
Problem with Eigen3

### ISSUE THREAD

**Issue by patrickelectric** [laurentkneip/opengv#3]
http://eigen.tuxfamily.org/index.php?title=Main_Page
I had rename the files of eigen3 to eigen in /usr/local/lib/cmake to compile the opengv.

/usr/local/lib/cmake/eigen3/Eigen3Config.cmake to /usr/local/lib/cmake/eigen3/EigenConfig.cmake
/usr/local/lib/cmake/eigen3/UseEigen3.cmake to
/usr/local/lib/cmake/eigen3/UseEigen.cmake 

but have some problems to make the opengv.
/usr/local/include/eigen3/unsupported/Eigen/NonLinearOptimization:15:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>

Dont have support to Eigen3 ?

**Comment by grandoba** [comment]
I solved the problem by changing the following:

* `find_package(Eigen Required)` to `find_package(Eigen3 Required)`  in line 161
* `include_directories(${EIGEN_INCLUDE_DIRS} ${EIGEN_INCLUDE_DIR}/unsupported)` to `include_directories(${EIGEN3_INCLUDE_DIRS} ${EIGEN3_INCLUDE_DIR}/unsupported)` in line 162
