### ISSUE TITLE
built python warppers on windows

### ISSUE THREAD

**Issue by xialang2012** [laurentkneip/opengv#31]
I have built the python wrappers on Windows with VS2013, and the installed folder structure likes below
> C:\Program Files\opengv\lib\python2.7\site-packages\pyopengv.lib
> C:\Program Files\opengv\lib\python2.7\site-packages\pyopengv.so
> C:\Program Files\opengv\lib\opengv.lib

Besides, the VS outputs like this

> 2>  -- Installing: C:/Program Files/opengv/lib/python2.7/site-packages/pyopengv.so
> ========== Build: 2 succeeded, 0 failed, 22 up-to-date, 0 skipped ==========

It hints it is already. Then, I tried to import the import pyopengv from the python, but it showed me 

> import pyopengv
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named pyopengv

On my Ubuntu, it works well, but I do not know why it is wrong on Windows.

**Comment by kafeiyin00** [comment]
can you compile the opengv in vs2013?
![image](https://cloud.githubusercontent.com/assets/10334862/19260618/a459bca6-8fbd-11e6-80fe-60de2db6f5be.png)

**Comment by laurentkneip** [comment]
Where is the error?
