### ISSUE TITLE
How to include opengv in my own cmake project?

### ISSUE THREAD

**Issue by johannesmik** [laurentkneip/opengv#34]
I would like to use opengv in my own opencv project, but I cannot figure out how to do that.

What method can **you recommend** to include OpenGV into a cmake project?

------------
What I  tried so far

I compiled and installed opengv like this:

    mkdir build
    cd build
    cmake -DINSTALL_OPENGV=ON ..
    make 
    sudo make install

In my project's CMakeLists.txt I tried to find Opengv, like this

    find_package( OpenGV REQUIRED)

but I got the following error (shortened):
```
[...]
  Could not find a package configuration file provided by "OpenGV" with any
  of the following names:
    OpenGVConfig.cmake
    opengv-config.cmake
[...]
-- Configuring incomplete, errors occurred!
```

Maybe I make a mistake by using find_package. I tried to read a bit on OpenCV but I could not get my head around it. It looks like if I wanted to use find_package then OpenGV should have a file called `OpengvConfig.cmake.in` that defines the include directories (see [here](https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file) ).

**Comment by simogasp** [comment]
For the moment the only way it's to write your FindOpenGV module to be included in your project. Feel free to use this one
https://github.com/poparteu/openMVG/blob/popart_develop/src/cmakeFindModules/FindOpenGV.cmake

S.

**Comment by johannesmik** [comment]
Thank you!

**Comment by pmoulon** [comment]
There is a pending PR that allows to use OpenGV as you suggested (find_package)
https://github.com/laurentkneip/opengv/pull/32
Feel free to use it.
