### ISSUE TITLE
Problem in installing opengv

### ISSUE THREAD

**Issue by hilman-dayo** [laurentkneip/opengv#36]
I am on Ubuntu 16.04.1. I have successfully `make` opengv, and `make test`. When I `make install` it, I got this error.  

```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libopengv.a
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/home/hilman-dayo/opengv/build/lib/libopengv.a" to
  "/usr/local/lib/libopengv.a".


Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
```

How can I fix this? I already set the INSTALL_OPENGV to ON during `cmake`.

**Comment by pmoulon** [comment]
You must be "sudo" when installing since you add file to system files.

**Comment by hilman-dayo** [comment]
Just figured that out. How silly of me. Thanks.
