### ISSUE TITLE
About the solution of 5 points relative pose method

### ISSUE THREAD

**Issue by riyueshi** [laurentkneip/opengv#39]
Hi,
  I got a question that some paper shows that to determine the Essential matrix by 5-points there are up to ten solution and how can we got the unique solution we want? (it seems many open source 5-points method result in an unique solution for essential matrix)
Thanks,
Miller

**Comment by laurentkneip** [comment]
It depends how many points you are using. If you only use five points,
there may be up to 10 solutions (usually less, always 10 including those in
the complex domain). Many algorithms can be run with more points, in which
case they may return only one solution. If you use only 5, you need to use
one additional point for disambiguation (by checking the reprojection
error).

**Comment by riyueshi** [comment]
Thanks for your illustrations. If I have many points but all those points are coplanar (or the additional point use for disambiguation is coplanar with those 5 points), does this coplanar conditions allows me to got a unique solution?

**Comment by laurentkneip** [comment]
No, the coplanar case is a degenerate one, you won't be able to get a
unique solution in general (even if using more points).

**Comment by riyueshi** [comment]
It means that it is not possible to do the stereo calibration by obtaining essential matrix using chessboard images (since we can not get a unique solution). The only way to perform stereo calibrate using chessboard images is using PNP to solve the pose of camera individually and then compute the relative rotation and translation just like openCV does, is that right?

**Comment by laurentkneip** [comment]
No that's wrong. Because for a checkerboard you will know for instance that
the corners need to lie on a regular grid. The points will only do so for
the correct solution, so you can use this criterion to perform
disambiguation of the multiple solutions.

**Comment by riyueshi** [comment]
Thanks a lot, your detailed illustration help me a lot. And I wonder is there any open source code perform the stereo calibrate by 5 point method using chessboard images?

**Comment by laurentkneip** [comment]
I don't know ...

**Comment by riyueshi** [comment]
Thanks.
