### ISSUE TITLE
Compiling under VC14 (Visual Studio 2015)

### ISSUE THREAD

**Issue by zziz** [laurentkneip/opengv#42]
I tried to build OpenGV under VC14
1. Errors due to Eigen: I wrote a workaroud code for this error, so there are no more error related to Eigen so far (see 2)
2. Compiling stops and Visual Studio doesn't respont (I can see 'Build failed' on left-down corner of Visual Studio, but cannot see error messages, so not sure what they are related, or even there is one or not). I force-close Visual Studio in this case. 
3. This is not related to VC14, but I want to mention it anyway. Building OpenGV (on VC11) takes really long time, about 2-3 hours on a fairly decent PC.

**Comment by fraztto** [comment]
How did you manage to fix the Eigen errors?
I'm currently facing a C2280 error around eigen types at solveInPlace function.

**Comment by fvzaur** [comment]
I couldn't finish building OpenGV in VC14 (Visual Studio 2015). As I mentioned before, it gets stuck at some point and computer seems to be force-restarted. In VS2013, there was no error related eigen as far as I remember. Please copy your error log here. Version of Eigen I used was 3.2.3.

**Comment by fraztto** [comment]
I've just figured it out, I changed a macro definition on the operator in macros.h for eigen. I was able to succesfully compile OpenGV and all the test programs.
