### ISSUE TITLE
ModuleNotFoundError: No module named 'pyopengv'

### ISSUE THREAD

**Issue by TopGun666** [laurentkneip/opengv#84]
Dear,
 I have installed successful on `ubuntu` , `python 3.6`. And `pyopengv.cpython-36m-x86_64-linux-gnu.so` can be found at` /usr/local/lib/python3/dist-packages/pyopengv.cpython-36m-x86_64-linux-gnu.so`.However, pyopengv can't be imported and  the `tests.py` in subfolder of `opengv` can't run.
Thanks
Yu.He

**Comment by nayanleo** [comment]
@TopGun666  i am having trouble to load pyopengv module, as i gone through your suggetion, but it won't work for me, also i installed python 3.6 for anaconda environment, does it affects the same.

**Comment by TopGun666** [comment]
> @TopGun666 i am having trouble to load pyopengv module, as i gone through your suggetion, but it won't work for me, also i installed python 3.6 for anaconda environment, does it affects the same.

I used `pip` envirronment, please check the position of `pyopengv.cpython-36m-x86_64-linux-gnu.so` and link it to `/path/python3.6/dist-packages/`.
